[book]
title = "Build an LLM from scratch with MAX"
authors = ["Modular <hello@modular.com>"]
description = "This guide walks you through implementing GPT-2 using Modularâ€™s MAX framework."
src = "src"
language = "en"
text-direction = "ltr"

[output.html]
additional-css = [
    "theme/css/custom.css",
    "theme/css/highlight.css",
]
additional-js = [
    "theme/code-highlighting.js",
    "theme/sidebar.js",
    "theme/init-amplitude.js",
    "theme/warning.js",
]
default-theme = "light"
preferred-dark-theme = "ayu"
smart-punctuation = true
no-section-label = true
git-repository-url = "https://github.com/modular/max-llm-book"
git-repository-icon = "fa-brands fa-github"
mathjax-support = true

[output.html.print]
enable = true

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[output.html.fold]
enable = false

[build]
build-dir = "html"
create-missing = true

[preprocessor.index]
index = false

[preprocessor.links]
# Enables use of {{#include file.md}} to include other files
renderers = ["html"]
some-attribute = "value"